In [55]:
import pandas as pd
import numpy as np

In [56]:
# loading the data
df = pd.read_csv('customer.csv')

In [57]:
df.sample(5)

age  gender   review education purchased
6    18    Male     Good    School        No
48   39  Female     Good        UG       Yes
25   57  Female     Good    School        No
0    30  Female  Average    School        No
2    70  Female     Good        PG        No

In [58]:
# lets separate the columns which are important to us for
# ordinal on the input dataset and label encoding on output dataset.
df = df.iloc[:,2:]

In [59]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [60]:
from sklearn.model_selection import train_test_split
# we will separate the training and testing data 1.rule before doing featuring
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2], df.iloc[:,-1], test_size=0.2)

In [61]:
X_train

review education
45     Poor        PG
1      Poor        UG
41     Good        PG
32  Average        UG
46     Poor        PG
28     Poor    School
24  Average        PG
11     Good        UG
47     Good        PG
3      Good        PG
44  Average        UG
17     Poor        UG
27     Poor        PG
6      Good    School
48     Good        UG
15     Poor        UG
23     Good    School
33     Good        PG
39     Poor        PG
21  Average        PG
35     Poor    School
26     Poor        PG
30  Average        UG
10     Good        UG
42     Good        PG
25     Good    School
5   Average    School
0   Average    School
8   Average        UG
49     Good        UG
19     Poor        PG
12     Poor    School
7      Poor    School
31     Poor    School
13  Average    School
9      Good        UG
29  Average        UG
37  Average        PG
22     Poor        PG
20  Average    School

In [62]:
X_train.shape

(40, 2)

In [63]:
from sklearn.preprocessing import OrdinalEncoder

In [64]:
# creating the Object for the ordinalEncoder
oe = OrdinalEncoder(categories=[['Poor','Average', 'Good'],['School', 'UG', 'PG']])

# we fir on train and we transform on train and test both

In [65]:
# now fitting the object on training data
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [66]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [67]:
X_train

array([[0., 2.],
       [0., 1.],
       [2., 2.],
       [1., 1.],
       [0., 2.],
       [0., 0.],
       [1., 2.],
       [2., 1.],
       [2., 2.],
       [2., 2.],
       [1., 1.],
       [0., 1.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [0., 1.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [1., 2.],
       [0., 0.],
       [0., 2.],
       [1., 1.],
       [2., 1.],
       [2., 2.],
       [2., 0.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [2., 1.],
       [0., 2.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [2., 1.],
       [1., 1.],
       [1., 2.],
       [0., 2.],
       [1., 0.]])

In [68]:
# we can also use categories feature like
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

# Now we will work with the purchased column that is categorical in output column we will use label encoding

In [69]:
from sklearn.preprocessing import LabelEncoder

In [70]:
# creating object for it
le = LabelEncoder()

In [71]:
le.fit(y_train)

LabelEncoder()

In [72]:
# To check which one is getting what
le.classes_

array(['No', 'Yes'], dtype=object)

In [73]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [74]:
y_train

array([1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1])

In [75]:
y_test

array([0, 1, 0, 0, 1, 0, 0, 0, 0, 1])